"""Add status to tasks

Revision ID: 4cbd363bbed1
Revises: b6dcbb7cfbd9
Create Date: 2024-02-14 22:44:04.859540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbd363bbed1'
down_revision = 'b6dcbb7cfbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Not Started', 'In Progress', 'Completed'), nullable=False, server_default='Not Started'))
        batch_op.alter_column('assigned_to',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('assigned_to',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
