"""empty message

Revision ID: edf7825dba2b
Revises: 72f963773123
Create Date: 2024-02-17 20:52:27.584198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf7825dba2b'
down_revision = '72f963773123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('In Progress', 'Completed'), nullable=True))
    
    # Update all existing rows to have 'In Progress' status
    op.execute("UPDATE projects SET status = 'In Progress'")
    
    # Alter 'status' column to not allow nulls now that all rows have been updated
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('feedbacks')
    # ### end Alembic commands ###
